### ISSUE TITLE
Failed to verify commit

### ISSUE THREAD

**Issue by wesleymotaaraujo** [SamhammerAG/last-successful-build-action#2]
Guys, I'm receiving these errors when I try to use the action. 
Could this be a bug or something else?

```
Run SamhammerAG/last-successful-build-action@v2
  with:
    branch: master
    workflow: Staging Deployment
    token: ***
    verify: false
Discovered workflowId for search: 
Getting list of SHAs in repo via command "git log --format=format:%H"
Looking for SHA 971723684194b9bc9a in repo SHAs
Warning: Failed to verify commit 971723 Skipping.
Looking for SHA 9[7]
Warning: Failed to verify commit bd2fb189bd770967147e105d481060e56714f728. Skipping.
Warning: Unable to determine SHA of last successful commit. Using SHA for current commit.
```

**Comment by mohammeduzair-oviva** [comment]
> Guys, I'm receiving these errors when I try to use the action. Could this be a bug or something else?
> 
> ```
> Run SamhammerAG/last-successful-build-action@v2
>   with:
>     branch: master
>     workflow: Staging Deployment
>     token: ***
>     verify: false
> Discovered workflowId for search: 
> Getting list of SHAs in repo via command "git log --format=format:%H"
> Looking for SHA 971723684194b9bc9a in repo SHAs
> Warning: Failed to verify commit 971723 Skipping.
> Looking for SHA 9[7]
> Warning: Failed to verify commit bd2fb189bd770967147e105d481060e56714f728. Skipping.
> Warning: Unable to determine SHA of last successful commit. Using SHA for current commit.
> ```

Check with this approach.

`- uses: actions/checkout@v2
        with:
          fetch-depth: 0 # check out the entire repo history for SHA verification
   `

**Comment by TeraNovaLP** [comment]
This issue should be fixed with v3.
