### ISSUE TITLE
If there is no current successful workflow, get a hash collision error.

### ISSUE THREAD

**Issue by birkses** [SamhammerAG/last-successful-build-action#4]
I am using last-successful-build-actionv4 and it works fine if there is a successful workflow deployment. However on a new branch with a new deployment the stage will fail and think there is a hash collision. 

I have tried with a fetch depth of 0 and 100.

The intended behavior would be to allow the step to pass, and give the current hash as described in the readme.md.

Error message:

Verifying git version...
  Valid git version found: (2.40.0)
  Running on a push event...
  Error: Similar commit hashes detected: previous sha: d40191fadf586b8e5f5d68b1dc4619c005430c27 is equivalent to the current sha: d40191fadf586b8e5f5d68b1dc4619c005430c27.
  Error: Please verify that both commits are valid, and increase the fetch_depth to a number higher than 50.
  Error: Process completed with exit code 1.

**Comment by domi2120** [comment]
@birkses  I've tried replicating this with a new branch and a new workflow that has not yet been run, which resulted in a workflow not found Error
![image](https://github.com/SamhammerAG/last-successful-build-action/assets/40773667/aa976113-a03b-476d-955c-da434f896fd8)
I've also tried it with a new branch and a workflow that has not successfully completed yet (also one which has not yet run in that branch), which resulted in the current hash being returned 
![image](https://github.com/SamhammerAG/last-successful-build-action/assets/40773667/4ffda160-fb65-4eb3-91db-acf51bf4c4bb)

Are there any other details that may be necessary to reproduce this issue?

**Comment by birkses** [comment]
Gday, @domi2120,

Sorry for the late reply, I have been unable to replicate the issue myself as well. Closing this issue as cant repro.

Thanks for you time.

Regards
