### ISSUE TITLE
Is there a way to find the last success by job name within the workflow?

### ISSUE THREAD

**Issue by zhaoyi0113** [SamhammerAG/last-successful-build-action#9]
I have a workflow includes a matrix job which could scale to many sub jobs. The last success commit is on workflow level. It doesn't work well if one of the matrix job fail but all others pass. Is there a way to specify another parameter to find the last success job?

**Comment by iamnafets** [comment]
Going to attempt a PR.

**Comment by iamnafets** [comment]
https://github.com/SamhammerAG/last-successful-build-action/pull/11

**Comment by gabbersepp** [comment]
closed by #11
